### ISSUE TITLE
cat8000v node definition not booting

### ISSUE THREAD

**Issue by lumean** [CiscoDevNet/cml-community#16]
Hi,
I'm trying to boot a cat8000v instance with IOS XE 17.6.2  using the c8000v-universalk9_8G_serial.17.06.02.qcow2  disk image from CCO.

Unfortunately it doesn't boot. I get the following error after few seconds of starting the node:
![image](https://user-images.githubusercontent.com/9656676/149943026-d05dc68e-7f85-44eb-ace6-3b742a353902.png)

CML Version  2.2.2+build52

I imported https://github.com/CiscoDevNet/cml-community/blob/master/node-definitions/cisco/cat8000v/cat8000v.yaml  and associate my node image with it:
![image](https://user-images.githubusercontent.com/9656676/149942654-96c6017d-a961-4bf8-96ec-451238924a37.png)

![image](https://user-images.githubusercontent.com/9656676/149942733-1271a553-84bf-4471-91e9-57e95baee5c1.png)

Any Idea how to troubleshoot?

**Comment by tbryan314** [comment]
@lumean - Thanks for the detailed question, but you'll probably get better help with general Cat 8000v troubleshooting in CML using the regular [CML Support](https://developer.cisco.com/docs/modeling-labs/#!support) channels.  

You'll definitely want to download the logs from the **CML2** page in [Cockpit](https://developer.cisco.com/docs/modeling-labs/#!logging-into-the-system-administration-cockpit).  You may be able to figure out what's going on from there, but CML support will definitely need to see those logs to troubleshoot the problem.

**Comment by xorrkaz** [comment]
@lumean, I agree with @tbryan314.  This doesn't seem as much an issue with the node def as an issue with your CML deployment.  Using the standard support channels would be preferred here.

**Comment by lumean** [comment]
Thanks for the quick replies, much appreciated! Yes, I noticed after posting that also some built-in node definitions have the same issue, so I agree it is a CML deployment issue, will follow the traditional support channels.
