### ISSUE TITLE
vir2-controller.service not starting

### ISSUE THREAD

**Issue by PFFernandes** [CiscoDevNet/cml-community#18]
After running the script vir2-migrate-data.sh from to 2.2.3+build63 to 2.3 the service "CML Controller" (virl2-controller.service) does not start.

11:29 AM
virl2-controller.service: Failed with result 'exit-code'.
systemd
11:29 AM
stop service (no-op)
virl2-controller.sh
11:29 AM
virl2-controller.service: Main process exited, code=exited, status=1/FAILURE
systemd
11:29 AM
(Background on this error at: https://sqlalche.me/e/14/e3q8)
virl2-controller.sh
11:29 AM
]
virl2-controller.sh
11:29 AM
)
virl2-controller.sh
11:29 AM
CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
virl2-controller.sh
11:29 AM
version_num VARCHAR(32) NOT NULL,
virl2-controller.sh
11:29 AM
CREATE TABLE alembic_version (
virl2-controller.sh
11:29 AM
[SQL:
virl2-controller.sh
11:29 AM
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
virl2-controller.sh
11:29 AM
cursor.execute(statement, parameters)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
virl2-controller.sh
11:29 AM
self.dialect.do_execute(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
virl2-controller.sh
11:29 AM
raise exception
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
virl2-controller.sh
11:29 AM
util.raise_(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
virl2-controller.sh
11:29 AM
self._handle_dbapi_exception(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
virl2-controller.sh
11:29 AM
ret = self._execute_context(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
virl2-controller.sh
11:29 AM
return connection._execute_ddl(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
virl2-controller.sh
11:29 AM
return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
virl2-controller.sh
11:29 AM
self.connection.execute(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
virl2-controller.sh
11:29 AM
return meth(obj, **kw)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
virl2-controller.sh
11:29 AM
visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
virl2-controller.sh
11:29 AM
bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 950, in create
virl2-controller.sh
11:29 AM
self._version.create(self.connection, checkfirst=True)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 539, in _ensure_version_table
virl2-controller.sh
11:29 AM
self._ensure_version_table()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 603, in run_migrations
virl2-controller.sh
11:29 AM
self.get_context().run_migrations(**kw)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
virl2-controller.sh
11:29 AM
File "<string>", line 8, in run_migrations
virl2-controller.sh
11:29 AM
context.run_migrations()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/db_migrations/alembic/env.py", line 86, in run_migrations_online
virl2-controller.sh
11:29 AM
run_migrations_online()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/db_migrations/alembic/env.py", line 92, in <module>
virl2-controller.sh
11:29 AM
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
virl2-controller.sh
11:29 AM
File "<frozen importlib._bootstrap_external>", line 848, in exec_module
virl2-controller.sh
11:29 AM
spec.loader.exec_module(module) # type: ignore
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
virl2-controller.sh
11:29 AM
module = load_module_py(module_id, path)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
virl2-controller.sh
11:29 AM
util.load_python_file(self.dir, "env.py")
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/script/base.py", line 563, in run_env
virl2-controller.sh
11:29 AM
script.run_env()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/alembic/command.py", line 613, in stamp
virl2-controller.sh
11:29 AM
command.stamp(cfg, product_version)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_core/persistence/persistence_manager.py", line 194, in alembic_stamp
virl2-controller.sh
11:29 AM
await self.alembic_stamp(alembic_cfg, product_version)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_core/persistence/persistence_manager.py", line 170, in stamp_cml2_db_version
virl2-controller.sh
11:29 AM
await self.stamp_cml2_db_version()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_core/persistence/persistence_manager.py", line 147, in prepare
virl2-controller.sh
11:29 AM
await db_handler.prepare()
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_ui/utils.py", line 147, in prepare_ui_manager
virl2-controller.sh
11:29 AM
ui_manager = await prepare_ui_manager(con_app.app, db_conn_str, use_mock_accessor)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_ui/webserver.py", line 206, in init_app
virl2-controller.sh
11:29 AM
return future.result()
virl2-controller.sh
11:29 AM
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
virl2-controller.sh
11:29 AM
con_app = loop.run_until_complete(init_app(args.port, args.db_conn_str, args.mock))
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/simple_ui/webserver.py", line 313, in main
virl2-controller.sh
11:29 AM
sys.exit(main())
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/bin/virl2_webserver", line 8, in <module>
virl2-controller.sh
11:29 AM
Traceback (most recent call last):
virl2-controller.sh
11:29 AM
The above exception was the direct cause of the following exception:
virl2-controller.sh
11:29 AM
sqlite3.OperationalError: attempt to write a readonly database
virl2-controller.sh
11:29 AM
cursor.execute(statement, parameters)
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
virl2-controller.sh
11:29 AM
self.dialect.do_execute(
virl2-controller.sh
11:29 AM
File "/var/local/virl2/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
virl2-controller.sh
11:29 AM
Traceback (most recent call last):
virl2-controller.sh
11:29 AM
E0325 11:29:27.969286 15928 devicemux.go:312] sync call connection refused -- trying again
virl2-devicemux.sh
11:29 AM
Version: 2.3.0+build22
virl2-controller.sh
11:29 AM
Copyright (c) 2020, 2021 Cisco Systems, Inc. and/or its affiliates
virl2-controller.sh
11:29 AM
>>> CML2 Controller
virl2-controller.sh
11:29 AM
_=/usr/bin/env
virl2-controller.sh
11:29 AM
OLDPWD=/
virl2-controller.sh
11:29 AM
DB_PATH=/var/local/virl2/config/controller.db
virl2-controller.sh
11:29 AM
LOG_DIR=/var/log/virl2
virl2-controller.sh
11:29 AM
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
virl2-controller.sh
11:29 AM
JOURNAL_STREAM=9:79859
virl2-controller.sh
11:29 AM
LD_LIBRARY_PATH=:/var/local/virl2/smart/lib
virl2-controller.sh
11:29 AM
DB_CONN_STR=sqlite:////var/local/virl2/config/controller.db
virl2-controller.sh
11:29 AM
SHLVL=1
virl2-controller.sh
11:29 AM
USER=www-data
virl2-controller.sh
11:29 AM
INVOCATION_ID=86d9dd3b707941e78ba23b0b9b0138c3
virl2-controller.sh
11:29 AM
LANG=C.UTF-8
virl2-controller.sh
11:29 AM
HOME=/var/local/virl2
virl2-controller.sh
11:29 AM
SMART_LOG_LEVEL=WARNING
virl2-controller.sh
11:29 AM
LOGNAME=www-data
virl2-controller.sh
11:29 AM
PWD=/var/local/virl2
virl2-controller.sh
11:29 AM
BASE_DIR=/var/local/virl2
virl2-controller.sh
11:29 AM
CFG_DIR=/var/local/virl2/config
virl2-controller.sh
11:29 AM
LOG_LEVEL=WARNING
virl2-controller.sh
11:29 AM
uid=33(www-data) gid=33(www-data) groups=33(www-data),124(wireshark)
virl2-controller.sh
11:29 AM
Started CML2 Controller.
systemd
11:29 AM
ERROR send-telemetry:111:HTTPConnectionPool(host='cml2-stats-1.virl.info', port=80): Max retries exceeded with url: /api/v0/telemetry-data/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f047e212880>: Failed to establish a new connection: [Errno -2] Name or service not known'))
virl2-controller.sh
11:29 AM
INFO send-telemetry:104:selected host: http://cml2-stats-1.virl.info/api/v0/telemetry-data/, 75 events to send
virl2-controller.sh
11:29 AM
INFO send-telemetry:82:['/usr/bin/journalctl', '--utc', '-o', 'json', '--since=@0.0', '_TRANSPORT=syslog', 'SYSLOG_FACILITY=22', 'SYSLOG_IDENTIFIER=virl2-telemetry']
virl2-controller.sh
11:29 AM
INFO send-telemetry:291:hours since last post: 457835.490272
virl2-controller.sh
11:29 AM
INFO send-telemetry:71:config: {"enabled": true, "timestamp": 0.0, "collectors": ["http://cml2-stats-1.virl.info", "http://cml2-stats-2.virl.info"], "random_uuid": "00000000-0000-0000-0000-000000000000"}
virl2-controller.sh
11:29 AM
{'category': 'VMWARE', 'timestamp': 1648207764.7814126, 'data': 'VMware ESX 6.7.0 build-16316930'}
virl2-telemetry
11:29 AM
INFO send-telemetry:82:['/usr/bin/vmware-toolbox-cmd', 'stat', 'raw', 'json', 'session']
virl2-controller.sh
11:29 AM
{"category": "MEMINFO", "timestamp": 1648207764.775785, "data": {"memtotal": {"amount": 65962592, "unit": "kB"}, "memfree": {"amount": 16698928, "unit": "kB"}, "memavailable": {"amount": 64553968, "unit": "kB"}, "buffers": {"amount": 33552, "unit": "kB"}, "cached": {"amount": 47081936, "unit": "kB"}, "swapcached": {"amount": 0, "unit": "kB"}, "active": {"amount": 554644, "unit": "kB"}, "inactive": {"amount": 46832676, "unit": "kB"}, "unevictable": {"amount": 0, "unit": "kB"}, "mlocked": {"amount": 0, "unit": "kB"}, "swaptotal": {"amount": 0, "unit": "kB"}, "swapfree": {"amount": 0, "unit": "kB"}, "dirty": {"amount": 2488, "unit": "kB"}, "writeback": {"amount": 0, "unit": "kB"}, "anonpages": {"amount": 272136, "unit": "kB"}, "mapped": {"amount": 127256, "unit": "kB"}, "shmem": {"amount": 1592, "unit": "kB"}, "kreclaimable": {"amount": 1407512, "unit": "kB"}, "slab": {"amount": 1641836, "unit": "kB"}, "sreclaimable": {"amount": 1407512, "unit": "kB"}, "sunreclaim": {"amount": 234324, "unit": "kB"}, "kernelstack": {"amount": 8416, "unit": "kB"}, "pagetables": {"amount": 7624, "unit": "kB"}, "nfs_unstable": {"amount": 0, "unit": "kB"}, "bounce": {"amount": 0, "unit": "kB"}, "writebacktmp": {"amount": 0, "unit": "kB"}, "commitlimit": {"amount": 32981296, "unit": "kB"}, "committed_as": {"amount": 2076756, "unit": "kB"}, "vmalloctotal": {"amount": 34359738367, "unit": "kB"}, "vmallocused": {"amount": 134284, "unit": "kB"}, "vmallocchunk": {"amount": 0, "unit": "kB"}, "percpu": {"amount": 33408, "unit": "kB"}, "hardwarecorrupted": {"amount": 0, "unit": "kB"}, "anonhugepages": {"amount": 0, "unit": "kB"}, "shmemhugepages": {"amount": 0, "unit": "kB"}, "shmempmdmapped": {"amount": 0, "unit": "kB"}, "filehugepages": {"amount": 0, "unit": "kB"}, "filepmdmapped": {"amount": 0, "unit": "kB"}, "cmatotal": {"amount": 0, "unit": "kB"}, "cmafree": {"amount": 0, "unit": "kB"}, "hugepagesize": {"amount": 2048, "unit": "kB"}, "hugetlb": {"amount": 0, "unit": "kB"}, "directmap4k": {"amount": 300396, "unit": "kB"}, "directmap2m": {"amount": 9136128, "unit": "kB"}, "directmap1g": {"amount": 59768832, "unit": "kB"}}}
virl2-telemetry
11:29 AM
{"category": "BLKINFO", "timestamp": 1648207764.7714796, "data": {"blockdevices": [{"name": "sda", "maj:min": "8:0", "rm": false, "size": "500G", "ro": false, "type": "disk", "mountpoint": null, "children": [{"name": "sda1", "maj:min": "8:1", "rm": false, "size": "512M", "ro": false, "type": "part", "mountpoint": "/boot/efi"}, {"name": "sda2", "maj:min": "8:2", "rm": false, "size": "31.5G", "ro": false, "type": "part", "mountpoint": null, "children": [{"name": "vg00-lv_root", "maj:min": "253:0", "rm": false, "size": "10G", "ro": false, "type": "lvm", "mountpoint": "/"}, {"name": "vg00-lv_var", "maj:min": "253:1", "rm": false, "size": "489.5G", "ro": false, "type": "lvm", "mountpoint": "/var"}]}, {"name": "sda3", "maj:min": "8:3", "rm": false, "size": "468G", "ro": false, "type": "part", "mountpoint": null, "children": [{"name": "vg00-lv_var", "maj:min": "253:1", "rm": false, "size": "489.5G", "ro": false, "type": "lvm", "mountpoint": "/var"}]}]}, {"name": "sr0", "maj:min": "11:0", "rm": true, "size": "7.9G", "ro": false, "type": "rom", "mountpoint": null}]}}
virl2-telemetry
11:29 AM
INFO send-telemetry:82:['/usr/bin/lsblk', '--json']
virl2-controller.sh
11:29 AM
{"category": "CPUINFO", "timestamp": 1648207764.7660758, "data": {"lscpu": [{"field": "Architecture:", "data": "x86_64"}, {"field": "CPU op-mode(s):", "data": "32-bit, 64-bit"}, {"field": "Byte Order:", "data": "Little Endian"}, {"field": "Address sizes:", "data": "43 bits physical, 48 bits virtual"}, {"field": "CPU(s):", "data": "24"}, {"field": "On-line CPU(s) list:", "data": "0-23"}, {"field": "Thread(s) per core:", "data": "1"}, {"field": "Core(s) per socket:", "data": "2"}, {"field": "Socket(s):", "data": "12"}, {"field": "NUMA node(s):", "data": "2"}, {"field": "Vendor ID:", "data": "GenuineIntel"}, {"field": "CPU family:", "data": "6"}, {"field": "Model:", "data": "79"}, {"field": "Model name:", "data": "Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz"}, {"field": "Stepping:", "data": "1"}, {"field": "CPU MHz:", "data": "2194.711"}, {"field": "BogoMIPS:", "data": "4389.42"}, {"field": "Virtualization:", "data": "VT-x"}, {"field": "Hypervisor vendor:", "data": "VMware"}, {"field": "Virtualization type:", "data": "full"}, {"field": "L1d cache:", "data": "384 KiB"}, {"field": "L1i cache:", "data": "384 KiB"}, {"field": "L2 cache:", "data": "3 MiB"}, {"field": "L3 cache:", "data": "360 MiB"}, {"field": "NUMA node0 CPU(s):", "data": "0-11"}, {"field": "NUMA node1 CPU(s):", "data": "12-23"}, {"field": "Vulnerability Itlb multihit:", "data": "KVM: Vulnerable"}, {"field": "Vulnerability L1tf:", "data": "Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled"}, {"field": "Vulnerability Mds:", "data": "Vulnerable; SMT Host state unknown"}, {"field": "Vulnerability Meltdown:", "data": "Vulnerable"}, {"field": "Vulnerability Spec store bypass:", "data": "Vulnerable"}, {"field": "Vulnerability Spectre v1:", "data": "Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers"}, {"field": "Vulnerability Spectre v2:", "data": "Vulnerable, IBPB: disabled, STIBP: disabled"}, {"field": "Vulnerability Srbds:", "data": "Not affected"}, {"field": "Vulnerability Tsx async abort:", "data": "Not affected"}, {"field": "Flags:", "data": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap xsaveopt arat md_clear flush_l1d arch_capabilities"}]}}
virl2-telemetry
11:29 AM
INFO send-telemetry:82:['/usr/bin/lscpu', '--json']
virl2-controller.sh
11:29 AM
{"category": "DMIINFO", "timestamp": 1648207764.7656765, "data": {"product_name": "VMware7,1", "product_version": "None", "sys_vendor": "VMware, Inc."}}
virl2-telemetry
11:29 AM
INFO send-telemetry:283:storing system information
virl2-controller.sh
11:29 AM
INFO send-telemetry:71:config: {"enabled": true, "timestamp": 0.0, "collectors": ["http://cml2-stats-1.virl.info", "http://cml2-stats-2.virl.info"], "random_uuid": "00000000-0000-0000-0000-000000000000"}
virl2-controller.sh
11:29 AM
prep service
virl2-controller.sh
11:29 AM
Starting CML2 Controller...

**Comment by tombry** [comment]
@PFFernandes  - Thanks for reporting this problem, but since this is a problem with the [documented migration process](https://developer.cisco.com/docs/modeling-labs/#!cml-release-notes) from CML 2.2.x to CML 2.3.0, please use the regular [CML Support](https://developer.cisco.com/docs/modeling-labs/#!support) channel to report this problem.  

If you can [log into Cockpit](https://developer.cisco.com/docs/modeling-labs/#!logging-into-the-system-administration-cockpit), then go ahead and download the CML logs for a time period that covers the failed start and attach the log bundle to your question.  That'll give the CML team a much cleaner view of this error message. 

Thanks!

**Comment by PFFernandes** [comment]
> @PFFernandes - Thanks for reporting this problem, but since this is a problem with the [documented migration process](https://developer.cisco.com/docs/modeling-labs/#!cml-release-notes) from CML 2.2.x to CML 2.3.0, please use the regular [CML Support](https://developer.cisco.com/docs/modeling-labs/#!support) channel to report this problem.
> 
> If you can [log into Cockpit](https://developer.cisco.com/docs/modeling-labs/#!logging-into-the-system-administration-cockpit), then go ahead and download the CML logs for a time period that covers the failed start and attach the log bundle to your question. That'll give the CML team a much cleaner view of this error message.
> 
> Thanks!

Hello @tombry ,

This is a personal license so....the only option available will be the CML Community Thanks anyway for the quick reply. 

Kind Regards
PF

**Comment by xorrkaz** [comment]
Moving to the community.
