### ISSUE TITLE
C9800-CL not accessible via Console

### ISSUE THREAD

**Issue by jiribrejcha** [CiscoDevNet/cml-community#2]
I use the "cat9800.yaml" node definition and IOS-XE 16.12.3 KVM QCOW2 image from Cisco.com, but I am not able to get past this console output on the controller. I waited about 30 minutes.

Running CML-Ent 2.0.1-b2

Have you seen this before? Any suggestions, please?

<img width="822" alt="Screenshot 2020-06-16 at 00 03 47" src="https://user-images.githubusercontent.com/18701525/84716845-2cbaf480-af6c-11ea-9e26-05593ea2bac0.png">

**Comment by xorrkaz** [comment]
I'm closing this issue.  Newer 9800 images apparently want a VGA console.  I've updated the notes here in the community to reflect that.
