### ISSUE TITLE
Unable to configure cumulus nodes in CML2 (custom image and node definition)

### ISSUE THREAD

**Issue by petersmiddy** [CiscoDevNet/cml-community#23]
Hello, I'm trying to configure a cumulus lab. I downloaded a cumulus vx qcow2 image, uploaded to CML as a new custom image, and downloaded the yaml file provided on this repo for node definition.
I'm able to add the cumulus nodes to the lab, but it will not let me configure anything. The qcow2 image I uploaded to CML is qemu-kvm one found here: [Cumulus VX Qcow2 image for KVM](https://www.nvidia.com/en-us/networking/ethernet-switching/cumulus-vx/) .  

Wondering if it's the image itself that is preventing me from being able to configure anything via 'net add' commands?

Thanks!
<img width="1121" alt="cannot-be-configured" src="https://user-images.githubusercontent.com/27960547/189199888-84870441-81fa-4262-85b1-6f4f7534b09f.png">
<img width="1183" alt="cumulus-net-add-not-working" src="https://user-images.githubusercontent.com/27960547/189199909-ada90252-1e90-4306-b6f6-07c67ea89c6f.png">

**Comment by xorrkaz** [comment]
I'm not familiar with Cumulus, but the message above from CML is expected.  There is no day0 config support for this node type.  As to why the `net add` command fails, seems like a syntax error.  You might want to try the `net help` command as it suggests to see the usage.  If you need more help, you'll need to check with Cumulus.
