### ISSUE TITLE
yang2dsdl issue on DevNet Expert Candidate Workstation

### ISSUE THREAD

**Issue by daniel1820815** [CiscoDevNet/cml-community#34]
I am not sure if it is the right place to address this issue. I tried to validate my YANG model with XML test data on the DevNet Expert CWS running in CML using yang2dsdl but I got an error that it failed to load external entity:

```bash
(main) $ yang2dsdl -v test-data.xml test-module.yang 
warning: failed to load external entity "/usr/local/share/yang/xslt/basename.xsl"
cannot parse /usr/local/share/yang/xslt/basename.xsl
== Generating RELAX NG schema './-data.rng'
warning: failed to load external entity "schema-dir"
cannot parse schema-dir
```

I solved the problem with setting the environment variables for PYANG:

```bash
(main) $ export PYANG_XSLT_DIR=$HOME/venvs/main/share/yang/xslte/yang/schema
(main) $ export PYANG_RNG_LIBDIR=$HOME/venvs/main/share/yang/schema
(main) $ 
(main) $ 
(main) $ 
(main) $ yang2dsdl -v test-data.xml test-module.yang 
== Generating RELAX NG schema './test-module-data.rng'
Done.
 
== Generating Schematron schema './test-module-data.sch'
Done.
 
== Generating DSRL schema './test-module-data.dsrl'
Done.
 
== Validating grammar and datatypes ...
test-data.xml validates
 
== Adding default values... done.
 
== Validating semantic constraints ...
No errors found.
(main) $ 
```

Not sure if it is a proper solution and I really don't know if it is a real issue but I think it should work when using the CWS during at home or during the lab exam.

If you need more data or if I should test anything please let me know, I am happy to help.

**Comment by xorrkaz** [comment]
Thanks for the report, Daniel, but this isn't the right project.  This community is more about CML, and we're just making the node def for CWS available.

With my DevNet Expert hat on, I would also say that you setting the envvars here looks like the right solution to what you're trying to do.  I would have also just used `pyang` myself (and I would have had to use `-p` to point to the right module path(s)).  Therefore, I see this more as an exercise for one using the system than a problem per se.

**Comment by daniel1820815** [comment]
Thanks @xorrkaz for the quick clarification and comment. I was unsure if it is an issue and where to address.
