### ISSUE TITLE
cat9000v-s1 bootstrap config not loaded

### ISSUE THREAD

**Issue by maercu** [CiscoDevNet/cml-community#35]
Hi team. I know it's a beta image but cat9k nodes don't load the bootstrap config if the autoinstall process is not manually canceled and an enable secret pw is provided (altough there is a complex enable secret in the bootstrap config). See https://community.cisco.com/t5/tools/cml-bootstrap-cat9000v/m-p/4898367

**Comment by xorrkaz** [comment]
This is a known issue with the C9Kv.  If you leave it, it will load the bootstrap config, but it will require some console interactivity.  This is what I wrote up for internal users:

>The day 0 config _does_ apply, but it takes a while. If you see the autoinstall menu, wait until you
see the message about trying DHCP on Gi0/0 before you hit any key. Also note that if you do
not have an enable secret configured, you will be prompted to configure one after answering,
“no” to the initial config dialog.
