### ISSUE TITLE
[BUG] - IOU L2 17.12.1 (Image From CML 7.1) Doesn't Support 802.1x?

### ISSUE THREAD

**Issue by WhatsTheIP** [CiscoDevNet/cml-community#46]
________________
= [Overview] =

Hey all, has anyone been able to test 802.1x for the following version IOU L2 Image:
- (X86_64BI_LINUX_L2-ADVENTERPRISEK9-M), Version 17.12.1, RELEASE SOFTWARE (fc5)

__________________________
= [Whats The Problem] =

Seems you can setup dot1x on the IOU L2 image, but the below commands do not work when you try to do basic verification:
- show authentication sessions
- show access-session
- show dot1x interface 

_____________
= [Testing] =

I re-ran the same configs I have on my IOU L2 image in my lab against the VIRL L2 image provided in CML 7.1 and the commands I outlined above (with the exception of "show access-session") works fine.

____________________________________________
= [Are There Other Reports Of This Bug?]

Yes, there appears to be another report, see below:
[1] - https://community.cisco.com/t5/network-access-control/802-1x-lab-not-working-edge-switch-won-t-send-authentication/m-p/4823237#M581422

**Comment by xorrkaz** [comment]
This is not the place to discuss general CML issues.  The proper location is the [CML community on Cisco Learning Network](https://learningnetwork.cisco.com/s/topic/0TO3i00000094ZjGAI/cisco-modeling-labs-personal-community).
